# config.yaml

# Dataset path
dataset:
    train_path: "/Users/abhaychaturvedi/Documents/Work/accelerators/classification_data"
    test_path: "/Users/abhaychaturvedi/Documents/Work/accelerators/classification_data"

# Model parameters
model:
    architecture: "vgg16"
    optimizer: "Adam"
    learning_rate: 0.001
    loss_function: "categorical_crossentropy"
    metrics: ["accuracy"]

# Training parameters
training:
    epochs: 2
    batch_size: 32

# Training parameters
testing:
    batch_size: 32

output:
    directory: "outputs"
    weights_name: "classification_model.pth"